// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTy4C0WNVhd9vKPy_DuyDmlqg1z2zI63U',
    appId: '1:27843234731:web:3ccdd541185efcc80720ee',
    messagingSenderId: '27843234731',
    projectId: 'airifier-a12aa',
    authDomain: 'airifier-a12aa.firebaseapp.com',
    storageBucket: 'airifier-a12aa.appspot.com',
    measurementId: 'G-LRX71M1RXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6TWxg09oFtKl7Z0wUk9-mHGvGIrdcXl4',
    appId: '1:27843234731:android:08aa8c2c2d629b3b0720ee',
    messagingSenderId: '27843234731',
    projectId: 'airifier-a12aa',
    storageBucket: 'airifier-a12aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrXpMQAuaHipy07DLBJ7-Z4qy2am-exwo',
    appId: '1:27843234731:ios:1331b062bbc8f42b0720ee',
    messagingSenderId: '27843234731',
    projectId: 'airifier-a12aa',
    storageBucket: 'airifier-a12aa.appspot.com',
    iosClientId: '27843234731-312ssa6kpn9g8vvf5gd7ugt4bqhku1jl.apps.googleusercontent.com',
    iosBundleId: 'com.example.aseProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrXpMQAuaHipy07DLBJ7-Z4qy2am-exwo',
    appId: '1:27843234731:ios:1331b062bbc8f42b0720ee',
    messagingSenderId: '27843234731',
    projectId: 'airifier-a12aa',
    storageBucket: 'airifier-a12aa.appspot.com',
    iosClientId: '27843234731-312ssa6kpn9g8vvf5gd7ugt4bqhku1jl.apps.googleusercontent.com',
    iosBundleId: 'com.example.aseProject1',
  );
}
